version: '3.9'

services:
  ingredient-ms:
    build: .
    container_name: ingredients-ms
    image: ingredients-microservice
    ports:
      - "8081:8081"
    environment:
      - db-url=jdbc:postgresql://ingredients-db:5432/ingredients_database
      - db-username=postgres
      - db-password=postgres
      - external-auth-url=http://jwt-user-auth:8080/tokenAuth/authenticate
    depends_on:
      - db
    restart: always
  db:
    ports:
      - "5433:5432"
    container_name: ingredients-db
    image: postgres:12
    environment:
      - POSTGRES_DB=ingredients_database
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - /var/lib/docker/volumes/ingredients-ms-volume/_data:/var/lib/postgresql/data
    restart: always
networks:
  default:
    name: app-ms
    external: true