server:
  servlet:
    context-path: /v1
  port: 8081

spring:
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5433/ingredients_database} # change postgres for the correct IP if running this app in a docker container or directly in your local env
    username: ${db-username:postgres} # super user
    password: ${db-password:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

external:
  auth:
    url: http://jwt-user-auth:8080/tokenAuth/authenticate